[package]
name = "entity"
version = "0.1.0"
edition = "2024"

[dependencies]
sea-orm = { version = "2.0.0-rc", features = [
    "macros",
    "runtime-tokio-rustls",
    "sqlx-sqlite",
    "schema-sync",
    "with-chrono",
    "with-uuid",
] }
serde = { version = "1.0.228", features = ["derive"] }
